### ISSUE TITLE
[Feature]: Add FTM mode in nucleus

### ISSUE THREAD

**Issue by rishabh-arya95** [LambdaTest/test-at-scale#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to add?

Adding FTM mode in nucleus

### Why should this be worked on?

Addin FTM mode in nucleus so as to run it as a separate task

**Comment by Shivanshu-lambdatest** [comment]
@rishabh-arya95 Please close this Issue, if  it is resolved.
